### ISSUE TITLE
`ecmHost` url base is not changed for API requests on nginx

### ISSUE THREAD

**Issue by shirosaki** [Alfresco/alfresco-content-app#2739] opened 2022-10-25 02:11 UTC
**Describe the bug**

Set in `app.config.json`:
`"ecmHost": "https://mydomain"`

`ecmHost` url base is not changed for API requests. It uses default base `/ecm`.
`GET /ecm/alfresco/api/xxxxxxxxx`

**Environment**
- ACA version: 3.0.0
- ACS version: 7.2

**To Reproduce**
1. change ecmHost in app/src/app.config.json.tpl.
`"ecmHost": "https://mydomain"`
2. npm run build.release
3. set nginx conf
```
        location /aca {
            alias  /path/to/alfresco-content-app/dist/content-ce;
            index index.html;
        }
```

4. open ACE via nginx in the browser and see nginx access log.

**Expected behavior**
`GET /alfresco/api/xxxxxxxxx`
without `/ecm`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102

**Additional context**
If I change the below default config, API url base is changed as expected.

https://github.com/Alfresco/alfresco-ng2-components/blob/1fa81962a047032210b2d0e00d6e56accf05b4db/lib/core/src/lib/app-config/app-config.service.ts#L67
changed from
`ecmHost: 'http://{hostname}{:port}/ecm',`
to
`ecmHost: 'http://{hostname}{:port}',`

**Comment by douglascrp** [comment] 2022-11-03 21:08
I am facing the same problem here, but using the latest 3.1.0 release.

**Comment by DenysVuika** [comment] 2022-11-06 11:00
Why do you set nginx path to `/aca`?

**Comment by DenysVuika** [comment] 2022-11-06 11:12
Maybe this nginx configuration gives more ideas: https://github.com/Alfresco/alfresco-content-app/blob/develop/docker/default.conf.template#L9

**Comment by douglascrp** [comment] 2022-11-07 11:44
> Why do you set nginx path to `/aca`?

I guess that does not matter, because the problem is not with ACA itself, but with the backend not being reachable because of the /ecm that is always included (as it is hardcoded in [the app.config](https://github.com/Alfresco/alfresco-ng2-components/blob/1fa81962a047032210b2d0e00d6e56accf05b4db/lib/core/src/lib/app-config/app-config.service.ts#L67)), and the backend is usually published as /alfresco.

**Comment by DenysVuika** [comment] 2022-11-07 14:08
@douglascrp if you check the source code, that line is actually the defaults that are used if no `app.config` data is found (loaded here https://github.com/Alfresco/alfresco-ng2-components/blob/1fa81962a047032210b2d0e00d6e56accf05b4db/lib/core/src/lib/app-config/app-config.service.ts#L176)... the `/ecm` part has been there for ages and has not changed, can be redefined in your proxy config or app config (https://github.com/Alfresco/alfresco-ng2-components/blob/about-box-collapsible/ALFRESCOCORS.md)

**Comment by douglascrp** [comment] 2022-11-07 18:51
In order to close this issue, I believe it's only required to have clearly described in the documentation that the app.config.json is going to be automacally generated after the .env is created, and the npm start command is executed.

After that, a ng build can be used in order to have the project ready to be deployed in the server.

**Closed** 2023-02-23 22:49 UTC
