### ISSUE TITLE
Dropdown List /Combo Box in ACS / ADF

### ISSUE THREAD

**Issue by hemantprasad** [Alfresco/alfresco-content-app#575] opened 2018-08-18 10:12 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/Alfresco/alfresco-content-app/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Though the ADF 2.5 has a dropdown list component in Metadata card/Info drawer components, but it doesn't pick values from custom property in ACS, which is configured with List of Values constraint.

## Expected behavior

Info Drawer / ADF 2.5 list box component should be able to fetch list of values from ACS custom property and possibly allow users to even add New Values, which can update List of values in ACS content model.
## What is the motivation / use case for changing the behavior?

Alfresco Share metadata form automatically shows the list of values configured in custom property. ADF / ACS Content App should behave the same way.

## Environment

<pre><code>
ACA version: X.Y.Z

Browser:
- [ ] Chrome version XX
- [ ] Firefox version XX
- [ ] Safari version XX
- [ ] Edge version XX
- [ ] IE11
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DenysVuika** [comment] 2018-09-21 15:11
Closing as duplicate of https://github.com/Alfresco/alfresco-ng2-components/issues/3709

**Closed by DenysVuika** 2018-09-21 15:11 UTC
