### ISSUE TITLE
On first load it says "This folder is empty" and then loads the files

### ISSUE THREAD

**Issue by THPubs** [Alfresco/alfresco-content-app#1182] opened 2019-08-08 07:10 UTC
**Describe the bug**
When you first load the app, it first says "This folder is empty". Then it shows a loading screen and loads the actual files. This happens in other places also. For example, if you go to Favourites, it will show the empty message first, then show the loading screen and later show the actual content.

**Environment**
- ACA version: 1.9.0

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the ACA
2. Login
3. This takes you to the initial screen which is the "Personal Files"
4. Now you'll see the empty message first
5. Next, you'll see the loading screen
6. Finally, you'll see your actual content

**Expected behaviour**
1. Show the loading screen
2. If there's content, load the content
3. If there's no content, show the empty message

**Screenshots**
![aca-empty](https://user-images.githubusercontent.com/1212023/62682314-82805100-b9d9-11e9-8a00-929462688c87.jpg)

**Desktop (please complete the following information):**
 - OS: OSX 10.14.16
 - Browser: Chrome, Brave

**Comment by john-knowles** [comment] 2019-08-08 21:51
Thank you for raising this; it is a known issue in the ADF and this app, see:
https://issues.alfresco.com/jira/browse/ADF-3796
https://issues.alfresco.com/jira/browse/ACA-1918

**Comment by THPubs** [comment] 2019-08-09 11:26
Ah cool. @john-knowles  So should I close this?

**Comment by DenysVuika** [comment] 2019-08-09 11:31
@THPubs we will close it once the issue is solved, no worries

**Comment by THPubs** [comment] 2019-08-09 11:56
Awesome!

**Comment by eromano** [comment] 2020-11-02 10:45
@THPubs can you try on the last version?

**Comment by eromano** [comment] 2021-03-30 13:35
Not able to reproduce on the last version please update and re-open if necessary

**Comment by digcat** [comment] 2021-04-17 09:26
Im still seeing this issue on the latest version, but it has changed slightly, in that you only see the "This folder is empty" the first time you access a folder, once accessed, the folders content appears without showing the message.  So to reproduce need to empty the browsers cache, then try access again.
![image](https://user-images.githubusercontent.com/4847462/115108260-5ca99e80-9f67-11eb-9474-134a479b064c.png)

**Comment by digcat** [comment] 2021-04-20 07:23
showing the error you can see the Folder is empty screen popping up even though the folder is not empty
[Personal Files - Alfresco Content Application - Google Chrome 2021-04-20 08-18-24.zip](https://github.com/Alfresco/alfresco-content-app/files/6341427/Personal.Files.-.Alfresco.Content.Application.-.Google.Chrome.2021-04-20.08-18-24.zip)

**Comment by dfirm** [comment] 2021-10-05 08:09
This issue is now fixed with 2.6 release, hooray :)

**Comment by dhrn** [comment] 2021-10-05 10:38
thank you @dfirm for the confirmation

**Closed by dhrn** 2021-10-05 10:38 UTC
Labels: bug, Mirrored in Jira
