### ISSUE TITLE
Metadata card not displaying custom group in the Recent Files navigation. It displays properly in "My Libraries" navigation 

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#923] opened 2019-02-08 15:29 UTC
**Describe the bug**
We have defined the custom preset in the app.extensions.json like below

```json
"content-metadata-presets": [
      {
        "id": "app.content.metadata.custom",
        "custom": [
          {
            "id": "app.content.metadata.customGroup",
            "title": "Test",
            "items": [

              {
                "id": "app.content.metadata.testAspect",
                "aspect": "test:TestDocument",
                "properties": [
                  "test:documentType",
                  "test:access",
                  "test:eligibility"
                ]
              }
            ]
          }
        ]
      }
    ]
```

Then the custom properties is getting displayed when we navigate to "My Libraries" and click on "i" icon. 

But when we navigate to recent files and click on "i" icon, the custom group is not displayed in the side panel.
**To Reproduce**
1. Go to Recent Files Navigation
2. Select the document
3. Click on "i" icon on top right corner.
4. You don't see customized metadata group.

**Expected behavior**
It should display the configured custom metadata.

**Screenshots**

**Comment by john-knowles** [comment] 2019-02-08 16:01
@nvmadhav - thank you for the feedback; we've created a ticket in our backlog for this - https://issues.alfresco.com/jira/browse/ACA-2194

**Comment by DenysVuika** [comment] 2019-02-13 14:26
@nvmadhav not sure if that helps but with the ACA 1.7 (development) and ACS Community 6.1.2.0 I am able to see custom aspect everywhere. 

I've created a custom model and aspect called `aca:denys` having an `aca:name` property inside. 
Then associated aspect with a file in Share, and declared the following preset

```json
"content-metadata-presets": [
      {
        "id": "app.content.metadata.custom",
        "custom": [
          {
            "id": "custom.aspect.demo",
            "title": "aca:denys",
            "items": [
              {
                "id": "aca:denys",
                "aspect": "aca:denys",
                "properties": "*"
              }
            ]
          }
        ]
      }
```

At runtime, in all the places where metadata is displayed, I can see it:

<img width="343" alt="screenshot 2019-02-13 at 14 21 29" src="https://user-images.githubusercontent.com/503991/52718406-4c6a9300-2f9b-11e9-90a9-4306b5785a99.png">

**Comment by nvmadhav** [comment] 2019-02-13 16:08
@DenysVuika  Is this in "Recent Files" navigation view or the regular view? I was able to see in other views except "Recent Files" view.

**Comment by DenysVuika** [comment] 2019-02-13 16:10
Recent Files is Search API query: [source code](https://github.com/Alfresco/alfresco-content-app/blob/development/src/app/services/data.service.ts#L68)

**Comment by nvmadhav** [comment] 2019-02-13 16:17
ya. Sorry looks like I was not clear. When I go to "Recent Files" and select a document, then click on "i" (information) icon then it was not showing the custom metadata view. But when I go to libraries and browse to a document and select that document and click on "i" then I was able to view the custom metadata. Not sure why as the component is same in both places. I have not tested with latest from development. I will test with development branch and will inform you.

**Comment by DenysVuika** [comment] 2019-02-13 16:20
The screenshot I made was for the "Recent Files", I have also tested with Files Component that backs Personal Files and Libraries.

**Comment by DenysVuika** [comment] 2019-02-27 13:31
Tested with ACS 6.1 -> cannot reproduce
Tested with ACS 5.2.4 -> issue can be reproduced

Closing this issue as 5.2.x APIs do not enable us to support this use case

**Comment by nvmadhav** [comment] 2019-02-27 15:31
@DenysVuika can you please provide more details which component uses the ACS6.1 service and about the service so that we will explore possibility of making it work for  5.2 version

**Comment by DenysVuika** [comment] 2019-02-27 15:33
@nvmadhav same component this issue is raised for: Metadata Card from ADF

**Comment by nvmadhav** [comment] 2019-02-27 20:23
@DenysVuika Little bit confused.Metadata component working in Favorites navigation and in the preview page but not working only in the recent files navigation. I need to still understand what ACS6.1 change impacting only recent files.

**Comment by DenysVuika** [comment] 2019-02-27 20:25
@nvmadhav just a guess - 6.1 has solr6 and various fixes to Search Services, we use Search API for recent files.

**Comment by nvmadhav** [comment] 2019-02-27 20:26
@DenysVuika We use Solr6 with search services 1.1.1. I know solr6 uses search services 1.2. Will dig into more to understand

**Comment by nvmadhav** [comment] 2019-02-27 20:51
@DenysVuika For me it looks like a bug. When I click on information icon, I didn't even see the calls going to metadata. And also initial call its making to favorites component and its not getting that document. You should be able to replicate this by selecting non-favorited document in Recent files. I will dig into more to see the actual root cause
/alfresco/api/-default-/public/alfresco/versions/1/people/-me-/favorites/8r4117a2-xxxx-4f5f-yyyy-ed919e43ef8e. Ideally as this document is not favorited, it shouldn't call favorites service

**Comment by DenysVuika** [comment] 2019-02-27 20:53
@nvmadhav as you already know, we do not support 5.x right now, and the issue is not reproduced with 6.x, that is why the ticket is closed.

**Comment by nvmadhav** [comment] 2019-02-27 23:00
@DenysVuika I think I found the problem Issue is in the content-app
https://github.com/Alfresco/alfresco-content-app/blob/master/src/app/components/info-drawer/info-drawer.component.ts
In the above file please refer the below method.
  private isRecentListFileNode(node: MinimalNodeEntity): boolean {
    return this.isTypeImage(node.entry) && !this.hasAspectNames(node.entry);
  }

Here we are allowing to load the node content only for the images. Ideally we should load the node info for all the documents. Not sure what exactly the purpose of having this condition. Also in case of Shared node, we are supposed to pass "entry.id" instead of "entry.nodeId". Can you please explain why do we have this condition for Recent files. Based on this condition, it should fail with ACS6.1 as well. Bit confused . sorry for multiple threads

**Comment by DenysVuika** [comment] 2019-02-28 06:52
I reopened the ticket and will investigate today. Thanks for details.

**Comment by DenysVuika** [comment] 2019-02-28 07:26
@nvmadhav Originally, we introduced Metadata prototype in ACA for images only, I think that's a very old block of code that needs to be removed. Good finding!

**Comment by nvmadhav** [comment] 2019-02-28 14:51
@DenysVuika Thanks for looking into this. Ideally irrespective of the navigation, here we should load the node information. I am not sure why are we loading the node info based on the condition. This is impacting if we write new navigational items. For new navigational items, we have to update this file for metadata component to work properly. Please consider this and provide generic solution here while fixing this.

**Closed** 2019-03-01 19:14 UTC
Labels: bug

**Comment by DenysVuika** [comment] 2019-07-19 07:28
@jigirshah we use GitHub issue tracker for bugs and feature requests, please use Gitter or Community portal for generic chats and questions.
