### ISSUE TITLE
Edit in Office: File is not getting unlocked after closing the word document

### ISSUE THREAD

**Issue by nvmadhav** [Alfresco/alfresco-content-app#943] opened 2019-02-13 18:21 UTC
**Describe the bug**
When User selects "Edit in Microsoft Office" system opens the word document. In ACA we can see the document got locked. But when user closes the word document, the document is not getting unlocked. It remains locked. This works fine from Alfresco share. 
Document remains locked even though user closed the word document.
**To Reproduce**
1. Go to a word document
2. Click on "Edit in Microsoft Office"
3. Modify the word document and you can see the changes reflected in ADF by refreshing
4. Once user closes the document, the document remains locked. Ideally it should unlock through aos calls. This works currently in Alfresco share.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by john-knowles** [comment] 2019-02-13 21:53
The work for Edit in Office is not fully implemented yet.  This is acceptance criteria number 4 here: https://issues.alfresco.com/jira/browse/ACA-214

**Comment by nvmadhav** [comment] 2019-02-13 21:57
I don't have access to that JIRA

**Comment by john-knowles** [comment] 2019-02-13 22:05
Updated it.

**Comment by nvmadhav** [comment] 2019-03-25 20:04
@john-knowles  With 1.7 upgrade still the acceptance criteria number 4 not working for us. This is mandatory functionality with "Edit in Office" and it works well with Alfresco Share. Please review

**Comment by john-knowles** [comment] 2019-03-26 21:12
Thanks @nvmadhav - yes we have a backlog item (https://issues.alfresco.com/jira/browse/ACA-2257) to dig into this, have updated the story to accurately reflect this outstanding item.

**Comment by DenysVuika** [comment] 2019-04-02 10:56
Will be fixed in 1.8

**Closed** 2019-05-03 06:09 UTC

**Comment by jperez1973** [comment] 2020-04-14 12:58
I have a similar problem, but in my case the user opens the document, then closes it without making any changes and it stays locked.

**Comment by DenysVuika** [comment] 2020-04-14 13:27
@jperez1973 does the state update if you reload the page?

**Comment by jperez1973** [comment] 2020-04-14 16:09
@DenysVuika yes, I can see "This document is locked by you." in share.

**Comment by DenysVuika** [comment] 2020-04-14 16:12
A browser is not allowed to watch desktop processes. Once you open MS Office, none of the browsers will get notified if you closed the app or not. You can raise a separate feature request to have some sort of timed polling to update the status of the node in UI, but it still won't be possible technically to know when your user close the desktop appication.

**Comment by jperez1973** [comment] 2020-04-14 16:50
Thanks for your quick reply @DenysVuika. We are using AOS to open the document for editing, we do get informed when the document is updated through a policy, isn't a similar way to get informed when it is closed? Thanks.

**Comment by DenysVuika** [comment] 2020-04-14 16:52
Javascipt application does not get that information because it operates with the public REST api.

**Comment by adinapitul** [comment] 2020-04-14 17:10
What version of ACA are you using, @jperez1973 ? This problem should be fixed in v1.9 afaik.

**Comment by adinapitul** [comment] 2020-04-14 17:14
Also, the ACS and Office versions might be important

**Comment by jperez1973** [comment] 2020-04-14 17:17
According to [official documentation](https://docs.alfresco.com/aos/concepts/aos-intro.html):

"Alfresco locks the file while it is being modified and releases the lock when the file is saved and closed.".

I'm not saying that a web app is going to receive this triggers, is Alfresco who receives this notifications:

1. Is notified when the document is being modified (locks the file).
2. Is notified when the document is saved and closed (releases the lock).

The problem seems to be if not all the steps are followed, this is to open and close the file without previous editing/saving.

**Comment by DenysVuika** [comment] 2020-04-14 17:21
@jperez1973 if your issue is related to the ACA, please raise a separate ticket and steps to reproduce, otherwise I suggest not to have any generic discussions re non-ACA topics inside this closed ticket
